-- Intentionally non-executable.
--
-- The database source of truth is the ordered migration chain in
-- supabase/migrations/. This file used to contain a stale pre-hardening schema
-- whose policies and views no longer matched production. Keeping a no-op file
-- preserves tooling/layout compatibility without offering an unsafe second
-- deployment path.
--
-- Validate a fresh database with:
--   supabase db start
--   supabase test db
--
-- Inspect migration state with:
--   supabase migration list --local
--   supabase migration list --linked
